### ISSUE TITLE
import SVG file into page on specific position

### ISSUE THREAD

**Issue by wimdevriendt** [arklumpus/VectSharp#1]
Hi i have svg icons which i need to put on one page and generate a pdf from in in vectorformat how can we do this ?

**Comment by arklumpus** [comment]
Hi, you need to install the `VectSharp`, `VectSharp.SVG` and `VectSharp.PDF` nuget packages. Then you can do something like this:

```CSharp
using System;
using VectSharp;
using VectSharp.PDF;

namespace SVGIconPDF
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create a new document
            Document outputDocument = new Document();
            
            // Create a new page and add it to the document
            Page page = new Page(500, 500);
            outputDocument.Pages.Add(page);

            // Access the page's Graphics object
            Graphics gpr = page.Graphics;

            // Open the icon file
            Page svgIcon = VectSharp.SVG.Parser.FromFile(@"C:\Users\Giorgio\Downloads\rocket.svg");
            Console.WriteLine("Nominal icon size: {0}x{1}", svgIcon.Width, svgIcon.Height);

            // Draw full-size icon at the origin
            gpr.DrawGraphics(0, 0, svgIcon.Graphics);

            // Draw resized 100x100 icon at (x, y) = (300, 400)
            double targetWidth = 100;
            double targetHeight = 100;

            double scaleX = targetWidth / page.Width;
            double scaleY = targetHeight / page.Height;

            gpr.Save();
            gpr.Scale(scaleX, scaleY);
            gpr.DrawGraphics(300 / scaleX, 400 / scaleY, svgIcon.Graphics);
            gpr.Restore();

            // Save the output as a PDF file
            outputDocument.SaveAsPDF("output.pdf");
        }
    }
}
```

Most SVG files should work fine, but bear in mind that VectSharp does not support 100% of the features of SVG. If you have a particular SVG file that is not loaded correctly, I'd be happy to have a look at it and see if the library can be updated to support it.

**Comment by wimdevriendt** [comment]
Hi I am unable to load the svg file into the document
In attachment you find a svg


Met vriendelijke groeten,

Wim De Vriendt
wimdevriendt@outlook.com<mailto:wimdevriendt@outlook.com>
+32(0)473 20 47 01

**Comment by wimdevriendt** [comment]
You can download 3 svg files with this link [https://www.pureautomation.be/downloads/icons.zip](https://www.pureautomation.be/downloads/icons.zip)

**Comment by arklumpus** [comment]
OK, the issue with those files was twofold: first, they specify the width and height in millimeters, which was causing the parser to fail. Second, they define the fill colour of the path using a CSS stylesheet, which was not supported.

If you try updating VectSharp.SVG to version 1.2.0, that should fix both issues. Let me know if it solves the problem for you!

**Comment by wimdevriendt** [comment]
Hi, my icons must have 10mmx10mm when i get height and size i get 1000 x 1000
what's the resolution you are using ?

**Comment by wimdevriendt** [comment]
Hi the pagesize is this in pixels ?

**Comment by wimdevriendt** [comment]
Hi i have problems with other icons as well can you check pls you can download them at [https://www.pureautomation.be/downloads/stickericons.zip](url)

**Comment by wimdevriendt** [comment]
Hi Can  you check all icons. Some of them are not showing good. Is this possible ?

**Comment by arklumpus** [comment]
Hi, so:

1) The resolution of the PDF file is 72dpi, which means that 10mm are equivalent to 10 / 25.3 * 72 ≈ 28.5 units in VectSharp.

2) The size that you get from Page.Width and Page.Height after loading an SVG file is the size of the SVG "viewbox". These are essentially arbitrary units that are used to define the coordinates of the objects in the file. You can use them to know how much you have to scale the image to get to a certain size: for example, to get a 10mm icon, you need to resize the image so that it has a width and height of 28.5 units, i.e. use a scaling factor of 28.5 / Page.Width (= 0.0285 if the icon's viewbox is 1000x1000).

3) The issue with the "window " icons was that the PDF output was using a non-zero fill rule. VectSharp.PDF version 2.1.2 fixes this by enabling the even-odd fill rulse, if you upgrade all the icons should work fine (see [stickericons.pdf](https://github.com/arklumpus/VectSharp/files/5202005/stickericons.pdf)).

**Comment by wimdevriendt** [comment]
Thanks for your fast answer. Can we also higher the pdf resolution or is this always by default 72dpi ?
For me it's  bit new

**Comment by wimdevriendt** [comment]
Hi I am missing something
I would think this would make a rectangle of 0.5 x 0.5 cm -> but it is always filling the complete box 1cm x 1cm

            //72dpi = 72 dot per inch ==> 2.83 = 1 mm
            Document doc1 = new Document();
            doc1.Pages.Add(new Page(28.3, 28.3)); //Add a new page with a size of 1cm x 1cm
            Graphics gpr1 = doc1.Pages.Last().Graphics; //Now, 1cm is 28.3 units
            //gpr1.FillRectangle(0, 0, 28.3, 28.3, Colours.Red); //Fill a 1cm x 1cm square
            gpr1.Scale(1000 / 28.3, 1000 / 28.3); //Now, 1cm is 1000 units
            gpr1.FillRectangle(0, 0, 500, 500, Colours.Red); //Fill a 1cm x 1cm square
            gpr1.Save();
            gpr1.Restore();
            // Save the output as a PDF file
            doc1.SaveAsPDF("output1.pdf");

**Comment by wimdevriendt** [comment]
the scale in your sample should be 28.3/1000. now its working

**Comment by wimdevriendt** [comment]
Hi everything works but now i need to rotate the complete graphics 180 degrees in the pdf how can i do that ?

**Comment by wimdevriendt** [comment]
Another question i need to streaam the pdf document to the user by 
MemoryStream memStream = new MemoryStream();
return memstream.toarray();

**Comment by arklumpus** [comment]
Yes, you are right, I fixed the sample!

If you want to rotate everything at the end without changing how you draw the icons in the first place, you could draw everything on a temporary `Graphics` first, then rotate the `Page`'s `Graphics` and draw the temporary `Graphics` on that.

Something like:

```CSharp
// Create a temporary Graphics object
Graphics uprightGraphics = new Graphics();

// Draw the icons on the uprightGraphics

// Width and height of the finished page.
double width = 28.3 * 8;
double height = 28.3 * 4;

// Create the actual document and page
Document doc = new Document();
doc.Pages.Add(new Page(width, height));
Graphics gpr = doc.Pages.Last().Graphics;

// Rotate by 180° around the centre of the page
gpr.RotateAt(Math.PI, new Point(width * 0.5, height * 0.5));

// Draw the temporary uprightGraphics
gpr.DrawGraphics(0, 0, uprightGraphics);
```

Returning the PDF as a byte array should be as simple as:

```CSharp
// Create the MemoryStream
using MemoryStream memStream = new MemoryStream();

// Write the document to the stream
doc.SaveAsPDF(memStream);

// Return as a byte array
return memStream.ToArray();
```

**Comment by wimdevriendt** [comment]
Hi, 
I have an issue with svg images with TEXT in it.
Can you look at the zip file. In the bin debug folder you find 2 pdfs, one with icon 20.svg and then icons are not aligned good
if i have no text in icons they appear good

you can find my test project in https://www.pureautomation.be/downloads/TestVectSharpConsole.zip
[https://www.pureautomation.be/downloads/TestVectSharpConsole.zip](url)

Can you have a look at it please ?
[TestVectSharpConsole.zip](https://github.com/arklumpus/VectSharp/files/5369506/TestVectSharpConsole.zip)

**Comment by arklumpus** [comment]
OK, this was due to a bug affecting SVG files with a text element with a transform containing one or more tspan elements (the graphics state was not properly restored after the tspan elements had been processed). I belive I have fixed this, it should work if you update VectSharp.SVG to version 1.2.1.

**Comment by wimdevriendt** [comment]
Hi it's working but is it normal i have to build for x64? If I use Any cpu i get badimage format exception and the reason is the dependency ExCSS.dll
That one is only working with x64
is that correct ?
thanks

**Comment by wimdevriendt** [comment]
I have downloaded all the sources and compiled with anycpu now it's working so i cannot use nuget packages
because the require x64

**Comment by wimdevriendt** [comment]
Hi, i have also another problem . the pdf generated with the application cannot be opened in Adobe Acrobat. Can you check what the reason is ?
the output pdf should be able to open in acrobat for a certaing program see my test application above and the pdf in attachment
[pdfErrorInAcrobat.pdf](https://github.com/arklumpus/VectSharp/files/5378629/pdfErrorInAcrobat.pdf)

**Comment by arklumpus** [comment]
About the compilation architecture, I have just released VectSharp 1.6.0, VectSharp.Canvas 2.1.5-preview5, VectSharp.PDF 2.1.3 and VectSharp.SVG 1.2.2 which are compiled using Any CPU, so they should work. VectSharp.MuPDFUtils and VectSharp.Raster remain x64-only though, because the MuPDF library requires native assets.

For once, the issue you have with that PDF seems to be a problem in your code, rather than in VectSharp 😀 Essentially, you are calling `Graphics.Restore()` without having called `Graphics.Save()` first. Since there is no state to restore if you have not saved it before, Adobe complains.

In any case, I have added a new feature in VectSharp 1.6.0 to prevent this. By default, VectSharp will now throw an exception if such a situation occurs. You can change this behaviour by changing the value of the static property `Graphics.UnbalancedStackAction`:

```CSharp
Graphics.UnbalancedStackAction = UnbalancedStackActions.Throw;
// This is the default: an exception will be thrown if the graphics state stack is unbalanced. I would strongly suggest keeping this setting and fixing the code if such an exception is thrown, because this usually means that there is something wrong going on (e.g. loops that save states without restoring them, or vice-versa).
```
```CSharp
Graphics.UnbalancedStackAction = UnbalancedStackActions.SilentlyFix;
// With this setting, VectSharp will try to automatically fix the unbalanced graphics state stack, trying to add or remove calls to Graphics.Restore() as necessary.
```
```CSharp
Graphics.UnbalancedStackAction = UnbalancedStackActions.Ignore;
// With this setting, VectSharp will not do anything to prevent an unbalanced graphics state stack (i.e. the previous behaviour until the introduction of this feature).
```

**Comment by wimdevriendt** [comment]
Hi Thanks again. Is there documentation how graphics works when to do save restore etc. I dont know much about it.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Giorgio Bianchini <notifications@github.com>
Verzonden: Wednesday, October 14, 2020 7:37:58 PM
Aan: arklumpus/VectSharp <VectSharp@noreply.github.com>
CC: Wim De Vriendt <wim@pureautomation.be>; Author <author@noreply.github.com>
Onderwerp: Re: [arklumpus/VectSharp] import SVG file into page on specific position (#1)


About the compilation architecture, I have just released VectSharp 1.6.0, VectSharp.Canvas 2.1.5-preview5, VectSharp.PDF 2.1.3 and VectSharp.SVG 1.2.2 which are compiled using Any CPU, so they should work. VectSharp.MuPDFUtils and VectSharp.Raster remain x64-only though, because the MuPDF library requires native assets.

For once, the issue you have with that PDF seems to be a problem in your code, rather than in VectSharp 😀 Essentially, you are calling Graphics.Restore() without having called Graphics.Save() first. Since there is no state to restore if you have not saved it before, Adobe complains.

In any case, I have added a new feature in VectSharp 1.6.0 to prevent this. By default, VectSharp will now throw an exception if such a situation occurs. You can change this behaviour by changing the value of the static property Graphics.UnbalancedStackAction:

Graphics.UnbalancedStackAction = UnbalancedStackActions.Throw;

// This is the default: an exception will be thrown if the graphics state stack is unbalanced. I would strongly suggest keeping this setting and fixing the code if such an exception is thrown, because this usually means that there is something wrong going on (e.g. loops that save states without restoring them, or vice-versa).

Graphics.UnbalancedStackAction = UnbalancedStackActions.SilentlyFix;

// With this setting, VectSharp will try to automatically fix the unbalanced graphics state stack, trying to add or remove calls to Graphics.Restore() as necessary.

Graphics.UnbalancedStackAction = UnbalancedStackActions.Ignore;

// With this setting, VectSharp will not do anything to prevent an unbalanced graphics state stack (i.e. the previous behaviour until the introduction of this feature).

**Comment by arklumpus** [comment]
Basically, when you use a function like `Graphics.Rotate()`, `Graphics.Translate()`, `Graphics.Scale()`, `Graphics.Transform()` or `Graphics.SetClippingPath()`, these affect the "state" of the Graphics object, so that the transformation (e.g. the scaling) is applied to all subsequent drawing actions.

If you wanted to apply the transformation only to some actions, you would have to manually revert it. For example, if you do `graphics.Scale(x, y);`, then draw something, and then you want to go back to the previous scaling, you would have to call `graphics.Scale(1 / x, 1 / y);`. Since this can get unnecessarily complicated when you are applying multiple transformations (as you would need to keep track of everything and then undo them exactly in the right order), the `Save`/`Restore` mechanism provides a way to achieve this more easily.

When you call `Graphics.Save()`, the current graphics state (including the rotation, scale, translation, clipping path etc) is saved. You can then use transformation functions, draw something, and then call `Graphics.Restore()`. This will restore the previously saved state, so that any transformation you used between the call to `Save` and the call to `Restore` will not be applied to the subsequent actions.

You may also want to read the section of the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) on the Graphics State (section 8.4 at page 121). Paragraph 8.4.2 describes the `q` operator (which is equivalent to `Graphics.Save()`) and the `Q` operator (which is equivalent to `Graphics.Restore()`). Note however that, of the elements described in Table 52, in VectSharp only the first two (_current transformation matrix_ and _current clipping path_) form part of the graphics state.

Also note the statement at the bottom of page 124: "Occurrences of the **q** and **Q** operators shall be balanced within a given content stream [...]", which explains the error you were getting.

**Comment by arklumpus** [comment]
I am closing this, feel free to reopen it (or create a new issue) if you still have any problem!
