### ISSUE TITLE
MuPDF dependencies

### ISSUE THREAD

**Issue by AlexanderMagdysyuk** [arklumpus/VectSharp#14]
Hi

The current Raster rendering looks strange, maybe remake it with https://www.nuget.org/packages/PortableGdi/ or https://www.nuget.org/packages/SixLabors.ImageSharp.Drawing?

For PDF there are options https://www.nuget.org/packages/PortablePdfSharpStd/ and https://www.nuget.org/packages/PdfSharpCore/ (good font resolver for PDFsharp can be found here: https://forum.pdfsharp.net/viewtopic.php?f=8&t=3976)?

Thanks.

**Comment by arklumpus** [comment]
Hi, can you clarify what you mean by looking strange? 😅 

The way VectSharp.Raster currently works is by first creating a PDF document, and then rendering the PDF with MuPDFCore (which provides .NET bindings for the native MuPDF). I know this is not ideal, but I have plans to rework this to use SkiaSharp instead (this is already used by one of the Avalonia Canvas renderers, so I would be able to reuse some code)... When I have time 😅 

I'm not sure, what is the issue with PDF?

**Comment by AlexanderMagdysyuk** [comment]
Ok, I am looking for a possibility to render image/svg/pdf in web assembly, so check if I can avoid native (as skia) dependencies.

**Comment by arklumpus** [comment]
Ah, I see... I will have a look and see if I can come up with an alternative! VectSharp.PDF and VectSharp.SVG should be fine though, as don't have any native dependency!

**Comment by arklumpus** [comment]
Ok, I have create [VectSharp.Raster.ImageSharp](https://www.nuget.org/packages/VectSharp.Raster.ImageSharp), which uses ImageSharp.Drawing to create the image. To install it you will have to add the ImageSharp MyGet source to your package sources, so that you can get the latest nightly version (the beta that is currently on NuGet throws an exception when you attempt to draw outside the page).

This does not have any native dependencies, but it is generally slower than using VectSharp.Raster:

![image](https://user-images.githubusercontent.com/32712606/148488415-f82aa258-2389-444d-b4f7-b03d4125a3a1.png)

This is interesting, it means that creating a PDF document and rendering is faster than just rendering the image, despite the additional step...

In any case, by using VectSharp.Raster.ImageSharp, VectSharp.PDF and VectSharp.SVG you should be able to generate PDF, SVG and BMP/GIF/JPEG/PBM/PNG/TGA/TIFF/WebP documents without any native dependency.

Have a look at the [overloads of the `SaveAsImage` and `SaveAsRawBytes` methods](https://giorgiobianchini.com/VectSharp/class_vect_sharp_1_1_raster_1_1_image_sharp_1_1_image_sharp_context_interpreter.html) to get an idea of what you can do.

I'm closing this, but feel free to reopen or to open another issue if you have any problems!

**Comment by AlexanderMagdysyuk** [comment]
This sounds really cool! Thanks for the update.
