### ISSUE TITLE
Possible dependencies license issue.

### ISSUE THREAD

**Issue by AlexanderMagdysyuk** [arklumpus/VectSharp#16]
VectSharp.Markdown is LGPL project.
It depends on MIT package https://www.nuget.org/packages/Highlight.NoEngine/9.0.0
Highlight.NoEngine depends on GPL package https://www.nuget.org/packages/VectSharp/1.7.0

Is it licensing chain issue?

**Comment by arklumpus** [comment]
It shouldn't matter, because when you install the LGPL version of VectSharp.Markdown, it will pull VectSharp 2.0.0; since 2.0.0 > 1.7.0, Highlight.NoEngine will not pull VectSharp 1.7.0 (hence, you will only get the LGPL versions).

In any case, I have released a new version of Highlight.NoEngine that references VectSharp 2.0.0 and correspondingly updated VectSharp.Markdown and VectSharp.MarkdownCanvas!
