### ISSUE TITLE
ImageSharp relies on ImageSharp.Drawing Preview release

### ISSUE THREAD

**Issue by PeteMichaud** [arklumpus/VectSharp#25]
My goal is to take a VectSharp page with graphics applied and output to an ImageSharp image object, which is exactly what the VectSharp.Raster.ImageSharp package is supposed to do, but VectSharp.Raster.ImageSharp depends on a version of ImageSharp.Drawing that isn't in NuGet yet, so even though it's on NuGet, it can never actually be installed using only NuGet. 

NuGet has beta14 where VectSharp depends on beta14.3. 

I'm already nervous using beta packages because I anticipate future maintenance problems, but I'd really rather not use unreleased packages if it can be helped. So I'm wondering if 14.3 is really actually necessary or if it was just what was convenient for you at the time of writing? And if it's not necessary, maybe you could push the dependency back to beta14 so it's possible to install VectSharp.Raster.ImageSharp via NuGet?

**Comment by PeteMichaud** [comment]
I pulled down the VectSharp repo and manually changed the version of ImageSharp.Drawing it was depending on, then built, and all the functionality works fine. I'd still like to get my custom VectSharp off my machine and put the dependency back on NuGet, but just so you know, at least the saving functionality works with beta14 instead of beta14.3

**Comment by arklumpus** [comment]
Thanks for pointing this out! The reason is that when I originally published VectSharp.Raster.ImageSharp, the latest version on NuGet was beta13, which had an annoying bug that caused an exception to be thrown whenever you attempted to draw outside the bounds of the image.

I have just released new versions of VectSharp.Raster.ImageSharp (1.1.2-beta14) and VectSharp.ImageSharpUtils (1.0.1-beta14) that depend on the beta14 in NuGet, which should work fine.
