### ISSUE TITLE
How to export SVG file as a PNG file?

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#28]
Hello:
I have a very simple SVG file, its content is just like this:
<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
   <circle cx="100" cy="50" r="40" stroke="black" stroke-width="4" fill="yellow" />
    <line x1="77" y1="27" x2="126" y2="73" stroke="red" stroke-width="10" />
    <line x1="77" y1="73" x2="122" y2="27" stroke="red" stroke-width="10" />
</svg>

I can use Inkscape to view it, it looks nice.  But when I want to export it as a PNG with size of 30X30 pixels, but the results are bad.  The picture is not in center.
I also tried to use some online tools to export it with size of 30X30, but all the results look ugly.
Can I use the repo to export a simple SVG like this one as a PNG file?
Thanks,

**Comment by arklumpus** [comment]
Hi! First of all, your SVG file does not have `width`, `height` or `viewBox` attributes, which means that it uses the default size of 300x150 units. Of course, trying to render that as a 30x30 PNG is going to look ugly (because the starting image is not square, and there is a lot of white space around the circle).

You should add at least a `viewBox` attribute to the `svg` element, e.g. by replacing the first line with something like this:

```XML
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="58 8 84 84">
```

Rendering the image with Inkscape or other tools should work better, then.

If you wanted to use VectSharp to rasterise this, you would need something like this:

```CSharp
using VectSharp;
using VectSharp.SVG;
using VectSharp.Raster;

// Open the SVG file.
Page pag = Parser.FromFile(@"C:\Users\Giorgio\Downloads\test.svg");

// You need this if you do not specify the viewBox in the SVG file. This will crop
// the image to the smallest size that contains all the graphics elements.
pag.Crop();

// The width you want for the output image.
double targetWidth = 30;

// Scaling factor.
double scale = targetWidth / pag.Width;

// Save the PNG file.
pag.SaveAsPNG(@"C:\Users\Giorgio\Downloads\test.png", scale);
```

The call to `pag.Crop` solves the issue of the missing `viewBox` attribute in this case.

<p align="center"><img src="https://user-images.githubusercontent.com/32712606/166125338-d3f0207d-a6de-447b-9f09-c484ab299cab.png"></p>

**Comment by zydjohnHotmail** [comment]
Hello:
Thank you very much, your code works.
But when I tried to write some code to draw a check mark as the following:
<svg class="done" xmlns="https://www.w3.org/2000/svg" viewBox="0 0 50 50">
    <circle class="circle" cx="22" cy="22" r="20" stroke="black" stroke-width="3" fill="yellow" />
    <path class="check"  stroke="red"  stroke-width="3" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
</svg>
I can see it some some online SVG viewer, but I can't use it in InkScape. I can use your code to show it, but what I want is I want to put it in InkScape, so I can put the checkMark a little higher, so it will be in the center of the circle.
But each time I used InkScape or other tools to load it, it failed.
Let me know what is the issue with the code.
Thanks,

**Comment by arklumpus** [comment]
The problem with this other SVG file is the namespace: you have `xmlns="https://www.w3.org/2000/svg"`, instead it should be `xmlns="http://www.w3.org/2000/svg"` (i.e., `http` instead of `https`). If you use `https`, the file will not be recognised as a valid SVG document.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your advice, it is working now.
