### ISSUE TITLE
How I can draw this SVG and save in PNG file using the repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#30]
Hello:
I found one SVG from this URL: https://rumble.com/upload.php
It is a white camera icon with green background.
I look at its SVG code, I want to save it as PNG using the repo., but I can't see viewable image when I open it with InkScape or other online SVG code editor.
The following is the SVG code:

<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 25 17">
<path fill="#fff" stroke-width="3" d="M13.24 9.3h-2.98v3a1 1 0 01-2.02 0v-3H5.26a1 1 0 110-2h2.98v-3a1 1 0 012.02 0v3h2.98a1 1 0 110 2M23.7 2.64l-4.67 2.7V4.32A4.32 4.32 0 0014.71 0H4.3A4.32 4.32 0 000 4.32v7.97a4.31 4.31 0 004.32 4.3H14.7a4.31 4.31 0 004.31-4.3v-1.02l4.67 2.7A.87.87 0 0025 13.2V3.4a.87.87 0 00-1.3-.76">
</path>
</svg>

There is one thing I am not sure if it is correct: stroke-width="3"
Let me know how I can change the code, so I can show and save it as a PNG file.  I want to make it with size: 64px by 64px.
Thanks,

**Comment by arklumpus** [comment]
Hi! I can't see the icon on the page you linked; in any case, the SVG seems to be _mostly_ fine, but the camera icon is white and doesn't have a green background. Therefore, when you open it in the browser or in Inkscape you can't see it, since it is drawn on a background that is also white.

However, opening it using VectSharp doesn't work, because the path data in the SVG file does not have a space separating the "flag" fields for the elliptical arc commands (which is technically valid SVG, but is not supported right now by VectSharp). To fix this, you can open the file in Inkscape and save it as a new file.

Once you do that, if you want to create a square 64x64 PNG file, you can do something like this:

```CSharp
using VectSharp;
using VectSharp.SVG;
using VectSharp.Raster;

// Open the SVG file.
Page pag = Parser.FromFile(@"path/to/input/file.svg");

// The width that you want for the output image
double targetWidth = 64;

// The height that you want for the output image
double targetHeight = 64;

// Scale factor - ensure that the image fits the output size
double scale = Math.Min(targetWidth / pag.Width, targetHeight / pag.Height);

// Output image size
Page outputPage = new Page(targetWidth, targetHeight);

// Add a green background if you want it, to make the icon visible.
outputPage.Background = Colours.Green;

// Center the image
outputPage.Graphics.Translate((targetWidth - pag.Width * scale) * 0.5, (targetHeight - pag.Height * scale) * 0.5);

// Scale using the scale factor
outputPage.Graphics.Scale(scale, scale);

// Draw the original image
outputPage.Graphics.DrawGraphics(0, 0, pag.Graphics);

// Save the PNG file
outputPage.SaveAsPNG(@"path/to/output/file.png");
```

<p align="center"><img src="https://user-images.githubusercontent.com/32712606/167943334-05845849-2bbf-4ce8-a4ee-406bd550bf31.png"></p>

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your quick fix.  But let me know how you get the green background.

**Comment by arklumpus** [comment]
You can set `outputPage.Background` to the background colour you want!

**Comment by arklumpus** [comment]
I'm closing this for now, feel free to reopen or to create another issue if you still have problems!
