### ISSUE TITLE
Saved SVG Color Is Different

### ISSUE THREAD

**Issue by broderickt2** [arklumpus/VectSharp#53]
Hi,

I noticed when I save a SVG that the color of it is different than what I expected. I looked through the documentation and the other issues and don't see much to go off. I think I might be missing something or maybe there is another issue. Any guidance or help you can provide would be much appreciated.

Here is some screenshots that show what I am seeing:
Before:
![image](https://github.com/arklumpus/VectSharp/assets/93213727/0336a704-53da-4f44-aa96-93bfa1c96385)

After:
![image](https://github.com/arklumpus/VectSharp/assets/93213727/7c979a16-dd94-4890-888f-3651aa2b684a)

As shown above in my screenshots, you will see that the after SVG that got saved is much darker than the original's colors, and the white laces on the ends of the ball don't exactly match up.

Here is the code I am using (essentially following the example from [here](https://giorgiobianchini.com/VectSharp/importing_svg.html)):
```
Dim myFile = Parser.FromFile("...\Football.svg")
Dim Page = New Page(myFile.Width, myFile.Height)
Dim Graphics = Page.Graphics

Graphics.DrawGraphics(0, 0, myFile.Graphics)

Page.SaveAsSVG("...\Test_Football.svg")
```

Here is the actual file I am using:
![Football](https://github.com/arklumpus/VectSharp/assets/93213727/3f748453-371a-403d-bd7e-b53cf6b51747)

Thanks in advance!

**Comment by arklumpus** [comment]
Hi! The issue was due to the fact that the SVG file uses gradients with "relative" coordinates rather than user-space coordinates (e.g., 0.5, 0.5 to point at the centre of the ball, rather than the actual coordinates).

I have just pushed VectSharp.SVG version 1.8.2-a8, which should now support this kind of gradients.

Please note that the SVG file also has some other issues - i.e., the gradient stops for some of the gradients (such as the white vertical bars) are specified in the wrong order (the gradient stop at offset 1 is specified first, then stop at intermediate offsets, then the stop at offset 0). Other SVG viewers (e.g., Inkscape or Chrome) are bothered by this and don't show the gradient in the right colour; VectSharp doesn't care and renders it correctly anyways.

Here is how the ball looks like when rendered with VectSharp.Raster (all the subtle differences are due to this issues with gradients in the SVG file):

![image](https://github.com/arklumpus/VectSharp/assets/32712606/b925d379-397b-481b-b36f-21f53f8bd20f)

**Comment by broderickt2** [comment]
You sir are working overtime! Thanks again for a deep explanation and pushing out a fix. I just pulled the prerelease and tested rendering the file myself; it looks much better! I attempted to try looking into the code for this issue myself and did speculate there was an issue somehow with how the gradients were being calculated.

In regards to the vertical white stripes missing the circles in them on the ends of the ball, I do see what you mean where Chrome is rendering that differently than from what I expected. Now I know to not always trust how Chrome is rendering SVG files. Regardless, I am glad the rendered raster image the library produces is correct.
