### ISSUE TITLE
Unable to use ZoomBorder (https://github.com/wieslawsoltes/PanAndZoom)

### ISSUE THREAD

**Issue by VincentDoan999** [arklumpus/VectSharp#57]
Unable to use ZoomBorder (https://github.com/wieslawsoltes/PanAndZoom) because it uses Avalonia 11.
Is there a plan to update VectSharp to Avalonia 11?

**Comment by arklumpus** [comment]
Hi! If you want to use Avalonia 0.10, you can use version version 0.10.14 of PanAndZoom.

In any case yes, I'm updating VectSharp.Canvas and the related packages to Avalonia 11, I just pushed VectSharp.Canvas 2.7.0-a5 to NuGet, this version works with Avalonia 11 (though I haven't tested it extensively).

**Comment by VincentDoan999** [comment]
Hi Giorgio,
That is wonderful! Thank you so much. Your work is amazing.

Vincent

**Comment by arklumpus** [comment]
I now released VectSharp.Canvas 2.7.0 which should work fine with Avalonia 11.

The only thing you may need to be aware of is that if you are using the `PaintToSKCanvas` method to place the rendering within a `ZoomBorder`, I would strongly recommend to set the `ClipToBounds` property to `true` on the `Control` returned by `PaintToSKCanvas`. Otherwise, when you zoom in, the canvas will attempt to render the whole image at a humongous resolution, even though most of it is outside of the client viewport.

I'm closing this for now, feel free to reopen or to create another issue if you have problems!

**Comment by VincentDoan999** [comment]
Thanks Giorgio!
Looking forward to try it.

Vincent
