### ISSUE TITLE
`Point.IsEqual` should use euclidian distance

### ISSUE THREAD

**Issue by gmkado** [arklumpus/VectSharp#61]
I would expect `Point.IsEqual` to return true if the euclidian distance (aka `sqrt((x1-x2)^2 + (y1-y2)^2)`) between it and `p2` is less than the tolerance.

Instead, looks like it checks both an absolute and normalized diff of each dimension individually against the tolerance.  Not sure if `IsEqual` is serving a purpose internally where this definition makes sense.

https://github.com/arklumpus/VectSharp/blob/7da0227c63e95ea88cf2ad5809bc55f325f55fb2/VectSharp/Point.cs#L101C13-L101C13

**Comment by arklumpus** [comment]
Yes, this is used in cases where you want to check whether two points are actually the same point, even when there might have been some loss of precision due to transformations etc. For example:

```CSharp
Point p1 = new Point(27, 0);
Point p2 = new Point(27, 0);
Point p3 = new Point(26.99999998, 0.0000001);

bool b1 = p1.Equals(p2);             // True
bool b2 = p1.Equals(p3);             // False
bool b3 = p1.IsEqual(p3, 1e-7);      // True
```

The documentation comments also describe this behaviour:

```XML
<returns><see langword="true"/> if both coordinates of the <see cref="Point"/>s are closer than <paramref name="tolerance"/> or if their relative difference (i.e. <c>(a - b) / (a + b) * 2</c>) is smaller than <paramref name="tolerance"/>. <see langword="false"/> otherwise.</returns>
```

If you wish to check whether two points are closer than a certain distance `r` in the Euclidean sense, you should compare it with the modulus of their difference (e.g., `(p1 - p2).Modulus() < r`).

**Comment by gmkado** [comment]
Ah I didn't see `Modulus`, thanks!
