### ISSUE TITLE
Can VectSharp be a replacement for SkiaSharp?

### ISSUE THREAD

**Issue by sgf** [arklumpus/VectSharp#66]
The SkiaSharp dll file is too large, close to 10mb.
I'm looking for a 2d graphics library developed in pure C#

**Comment by arklumpus** [comment]
Hi! Depending on what you want to do, it might be. If you just wish to create graphics (including animations) and export them in various vector and raster formats (e.g. SVG, PDF, PNG, JPEG, etc), then you can certainly use VectSharp.

If you are using SkiaSharp for some more low-level things, like high-performance rendering loops with GPU acceleration or drawing directly to the screen, it might not work as a replacement.

Note that if you wish to avoid extra DLLs and you need raster output (e.g., PNG or JPEG), you should use the VectSharp.Raster.ImageSharp output layer, rather than VectSharp.Raster (which uses a native DLL for better performance).

Happy to give more suggestions if you can be more specific about your use case!

**Comment by sgf** [comment]
alright, thank you very much.
