### ISSUE TITLE
Markdown with different context values per block

### ISSUE THREAD

**Issue by manutiedra** [arklumpus/VectSharp#69]
Right now, in VectSharp.Markdown the MarkdownRenderer methods Render and RenderSinglePage create a MarkdownContext to render all the blocks. 

That makes it very difficult to do things like draw parragraphs of different colours, use different fonts in different parragraphs, etc.

It would be nice to add a property BlockContext of type Func<MarkdownContext, Block, int, MarkdownContext> that is called before the RenderBlock calls and by default it returns the same MarkdownContext that is passed.

**Comment by manutiedra** [comment]
Thinking more about it, the Block parameter in the Func should be removed. If you are going to change the MarkdownContext you can use the function that uses the MarkdownDocument and access the block by index

**Comment by arklumpus** [comment]
Have a look at VectSharp.Markdown 1.7.0-a1, I have added a few events on the `MarkdownRenderer` class which should be able to do what you want:

* `PageStarted`, which is invoked when a new page has been started (before drawing anything on it).
* `PageFinished`, which is invoked after a page has been fully rendered (either at the end of the document, or just before starting a new page).
* `BlockRendering`, invoked just before rendering a `Markdig.Syntax.Block`.
* `BlockRendered`, just after the block has been rendered.
* `InlineRendering`, just before rendering a `Markdig.Syntax.Inlines.Inline`.
* `InlineRendered`, just after rendering the inline.
* `LineMeasured`, invoked after measuring the content of a `VectSharp.Markdown.Line`, but before rendering it. At this stage you can still make changes to the line (e.g., adding or removing `LineFragments`), because everything is going to be measured again.
* `LineRendering`, invoked just before rendering a line. At this stage you should not make any changes to the `Line`, because it will not be measured again.
* `LineRendered`, just after the line has been rendered.

The `EventArgs` for each of these events have some properties that can be `set` (e.g., the `MarkdownContext`); if you change the value of these properties, this will have an effect on the subsequent rendering. For example:
* The `BlockRenderingEventArgs` class has a settable `Block` property. If you change the value of this property, the new `Block` will be rendered instead of the original one (and if you set this to `null`, the block will be skipped).
* The `BlockRenderedEventArgs` also has a `Block` property, but this cannot be `set` (because the block has already been rendered, so it doesn't make sense to change it).

I hope this works, let me know if there is still something you can't do with these events!
